[project]
name = "medline-full-open-access-journals"
version = "0.1.0"
description = "Generate list of journals indexed in the DOAJ and MEDLINE"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ 
    "polars",
    "requests",
    "xlsxwriter",
]
